block_ip:
  requests:
    amount: 3
    time_window_seconds: 30
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-components: always
      show-details: always